### ISSUE TITLE
Character conversion error:

### ISSUE THREAD

**Issue by jcoyne** [dpla/rdf-marmotta#9]
```
     Encoding::UndefinedConversionError:
       "\xD7" from ASCII-8BIT to UTF-8
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:168:in `encode!'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:168:in `readline'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:185:in `consume'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:160:in `whitespace'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:113:in `get_token'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:105:in `token'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader/parser.rb:88:in `parse'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-n3-1.1.2/lib/rdf/n3/reader.rb:98:in `each_statement'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sparql-client-1.1.3.1/lib/sparql/client/query.rb:296:in `each_statement'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/rdf-marmotta-0f51cb3a192e/lib/rdf/marmotta.rb:49:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:149:in `grep'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:149:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each_statement'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/writable.rb:129:in `insert_statements'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/writable.rb:32:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/mutable.rb:71:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:264:in `reload'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:80:in `initialize'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:53:in `new'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:53:in `from_uri'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:174:in `make_node'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:158:in `convert_object'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:32:in `block in result'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block (2 levels) in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:341:in `call'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:341:in `block (4 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:339:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:339:in `block (3 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:336:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:336:in `block (2 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:333:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:333:in `block in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:330:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:330:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:85:in `query'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/model/graph.rb:270:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `each_with_object'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `result'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:9:in `as_json'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `map'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:159:in `as_json'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:34:in `encode'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/json/encoding.rb:21:in `encode'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-fedora-9.0.2/lib/active_fedora/profile_indexing_service.rb:8:in `export'
```

**Comment by jcoyne** [comment]
It's hitting this url:
```
curl -i "http://localhost:8180/marmotta/sparql/select?query=CONSTRUCT%20%7B%20?s%20?p%20?o%20.%20%7D%20WHERE%20%7B%20?s%20?p%20?o%20.%20%7D"
```

**Comment by jcoyne** [comment]
Getting lines like this:
```
<http://www.w3.org/2004/02/skos/core#altLabel> "קליפורניה"@en ;
```

**Comment by jcoyne** [comment]
"קליפורניה".force_encoding(Encoding::ASCII_8BIT).encode!(Encoding::UTF_8)
Encoding::UndefinedConversionError: "\xD7" from ASCII-8BIT to UTF-8

**Comment by jcoyne** [comment]
Looks like a potential bug in RDF::N3::Reader::Parser

**Comment by jcoyne** [comment]
See https://github.com/ruby-rdf/rdf-n3/issues/16

**Comment by no-reply** [comment]
This was closed via the linked issue.
